### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by elicharlese** [DASHED-OS/DASHED#10]
## 🔁 Ready for the sprint?
The "Security" Epic is focused on enhancing the security of the system. The primary objective of this epic is to identify and mitigate any vulnerabilities that exist within the system, ensuring that sensitive data is well-protected from any potential threats. This epic will involve implementing various security measures, such as access control, data encryption, and secure authentication mechanisms. Additionally, the team will be responsible for conducting regular security audits and penetration testing to identify and address any potential security issues. Overall, the goal of the Security Epic is to provide a secure environment for the users, ensuring that their data is safe and protected at all times.
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.

💬Any additional notes to the sprint should be placed within the chat below so that we can refer to the updates linearly.

### Sprint Planning

<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```ruby
   puts "Hello World"
```

</p>
</details>

### Daily Scrum

<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```ruby
   puts "Hello World"
```

</p>
</details>

### Sprint Review

<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```ruby
   puts "Hello World"
```

</p>
</details>

### Retrospective

<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```ruby
   puts "Hello World"
```

</p>
</details>

## Using a container?
```bash
docker run -g 
```
```bash
redhat run -g
```

## Org Chart
| Scrum Role               | GitHub username |         Discord      |
| :---                            |         :----:              |           :----:        |
| **Scrum Master**     |  @elicharlese        | bangobongo17 |
| **Product Owner**   | Text                       | And more          |
| **Developer**           |                              |                           |

--------------------------------
[An ECE Dapp](https://github.com/elicharlese)

**Comment by elicharlese** [comment]
## Security: [Gitcoin Passport](https://passport.gitcoin.co/)

[Documentation](https://docs.passport.gitcoin.co/building-with-passport/quick-start-guide)

- [ ] [CEC](https://gitpod.io/projects/app-41a1324f-ab06-4f9e-b598-7b2802136ff2)
- [ ] [TS](https://gitpod.io/projects/app-cc1bca8e-4846-4e73-8aa2-45d3c094839a)
- [ ] [TDT](https://gitpod.io/projects/app-48e8ebfa-7a84-4393-b18a-9c59cce38705)
- [ ] [SPECTRA](https://gitpod.io/projects/SPECTRA-1b43b324-a758-49cc-b56c-faff15082e17)
- [ ] [OMNI](https://gitpod.io/projects/OMNI-f7e5cf93-4cd4-4550-b949-f0cae1d0273e)
- [ ] [DASHED](https://gitpod.io/projects/DASHED-d95c64e9-2bbd-4c1a-ac09-9bb137602de9)
- [ ] [GSL](https://gitpod.io/projects/GSL-e56441f3-0e79-4593-84ec-6e6270f4c6a6)
